language: node_js
sudo: required
node_js: 
  - 7.9.0

cache:
  directories:
    - node_modules

branches:
  only:
    - hexo 

before_install:
  - npm install -g hexo-cli

# S: Build Lifecycle
install:
  - npm install
  - npm install hexo-deployer-git --save

before_script:
 # - npm install -g gulp

script:
  - hexo clean
  - hexo generate

after_script:
  - git config user.name "xiongxunxiang"
  - git config user.email "xiongxunxiang_it@163.com"
  - sed -i "s/baidu_token/${Baidu_Url_Submit_Token}/g" ./_config.yml
  - sed -i "s/gh_token/${GH_TOKEN}/g" ./_config.yml
  - sed -i "s/coding_token/${Coding_TOKEN}/g" ./_config.yml
  - cat ./_config.yml
  - hexo deploy
# E: Build LifeCycle

